<a href="https://colab.research.google.com/github/gptix/data-visualization/blob/master/Copy_of_Copy_of_Plant_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
# Import libraries probably needed.
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
from numpy import array
from numpy import linalg as la

import seaborn as sns

from urllib.request import urlopen
from zipfile import ZipFile
from io import BytesIO
import os.path

import pandas as pd

from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans

from functools import reduce
from math import sqrt

import random
from statistics import mean, stdev

# import plotly.plotly as py 
# import plotly.graph_objs as go

In [0]:
# import csv files
path_base = 'https://raw.githubusercontent.com/gptix/data-visualization/master/'


def fn_to_df(fn, skiprows_x = 0): 
  url = path_base + fn
  return (pd.read_csv(url, skiprows=skiprows_x))

filename1 = '2___Plant_Y2018.csv'
filename2 = '3_1_Generator_Y2018.csv'
filename3 = 'EIA923_Schedules_2_3_4_5_M_12_2018_Final_Revision.csv'

# Passing in '1' to skiprows_x to trim useless first row.
# plants_df = fn_to_df(filename1, 1)
generators_df = fn_to_df(filename2, 1)
# detail_df = fn_to_df(filename3)

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2822: DtypeWarning: Columns (0,15,38,42) have mixed types. Specify dtype option on import or set low_memory=False.
  if self.run_code(code, result):

In [0]:
df1.head()
df.tail()
df.isnull().count().sum()
# examine
# head
# tail
# shape
# Decsribe
# dtypes
generators_df.head(2)

  Utility ID  ... Switch Between Oil and Natural Gas?
0        195  ...                                 NaN
1        195  ...                                 NaN

[2 rows x 73 columns]

In [0]:
# filter detail to only those using coal
# join detail to generator on 
['Conventional Steam Coal', 'Coal Integrated Gasification Combined Cycle']